language: generic
services:
  - docker

# Build Lifecycle
#   - before_install
#   - install
#   - before_script
#   - script
#   - after_success or after_failure
#   - after_script
#   - OPTIONAL before_deploy
#   - OPTIONAL deploy
#   - OPTIONAL after_deploy

after_success:
  # Be aware that you must use your docker hub username in the image tag
  # in the format <docker-hub-username>/<image-tag-name>
  # in order to successfully upload it to docker hub in the next step
  - docker build -t bl00na/os-voting-app-vote-python -f ./vote/Dockerfile ./vote
  - docker build -t bl00na/os-voting-app-vote-vuejs -f ./vote/Dockerfile-vuejs ./vote
  - docker build -t bl00na/os-voting-app-worker-java -f ./worker/Dockerfile ./worker
  - docker build -t bl00na/os-voting-app-worker-dotnet -f ./worker/Dockerfile-dotnet ./worker
  - docker build -t bl00na/os-voting-app-result-nodejs -f ./result/Dockerfile ./result
    # This Dockerfile uses the Microsoft Nano Server base OS image that reqires the host OS version to match the container OS version.
  # With Travis CI used that prerequisite is not fulfilled, thus the image build and push steps are commented out in this file.
  #- docker build -t bl00na/os-voting-app-result-dotnet -f ./result/Dockerfile-dotnet-sac2016 ./result
  
  # Log in to the docker CLI - the parameters are set up in Travis CI beforehand
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Push the images created to docker hub
  - docker push bl00na/os-voting-app-vote-python
  - docker push bl00na/os-voting-app-vote-vuejs
  - docker push bl00na/os-voting-app-worker-java
  - docker push bl00na/os-voting-app-worker-dotnet
  - docker push bl00na/os-voting-app-result-nodejs
  # This Dockerfile uses the Microsoft Nano Server base OS image that reqires the host OS version to match the container OS version.
  # With Travis CI used that prerequisite is not fulfilled, thus the image build and push steps are commented out in this file.
  #- docker push bl00na/os-voting-app-result-dotnet